In [2]:
import numpy as np

# BASIC

In [3]:
a = np.array([1,2,3],)
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get Shape
b.shape

(2, 3)

In [7]:
# Get Type
a.dtype

dtype('int64')

In [8]:
# Get Size
a.itemsize

8

In [9]:
# Get total size
a.nbytes

24

In [10]:
# Get number of elements
b.size

6

# Accessing/Changing specific elements, rows, columns, etc

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# Get a specific element [row, column]
a[1, 5]

np.int64(13)

In [13]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific row 
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [15]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [16]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [17]:
# changing elements
a[1,5] = 20

In [18]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [19]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [20]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

3d- array example

In [21]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
c.ndim

3

In [23]:
c.shape

(2, 2, 2)

In [24]:
# Get specific element (work outside in)

c[0,1,1] 

# 0 → Selects the first block (depth index).
# 1 → Selects the second row inside that block.
# 1 → Selects the second element in that row.

np.int64(4)

In [25]:
# Print 8
c[1,1,1] 

np.int64(8)

In [26]:
# replace 
c[:,1,:] = [[9,9],[8,8]]

# : → Select all matrices or blocks.
# 1 → Select the second row (index 1) from each matrix.
# : → Select all columns from that row of every block.

In [27]:
c

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [28]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
# All 1s matrix
np.ones((4,3,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [30]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [31]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [32]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [33]:
# Random decimal numbers

np.random.rand(4,4)

# np.random.rand(rows, columns) always generates decimal numbers because it picks values randomly from the range 0 to 1 (excluding 1). 
# It is designed to work with floating-point numbers, not integers.

array([[0.08280403, 0.80557188, 0.01161176, 0.67811085],
       [0.67894371, 0.3938466 , 0.36832257, 0.70433872],
       [0.28449882, 0.89067904, 0.39037068, 0.10003198],
       [0.92984692, 0.42831702, 0.46462692, 0.35178948]])

In [34]:
# Random decimal numbers

np.random.rand(4,4).reshape(8,2)

# np.random.rand(rows, columns) always generates decimal numbers because it picks values randomly from the range 0 to 1 (excluding 1). 
# It is designed to work with floating-point numbers, not integers.

array([[0.14122016, 0.91586584],
       [0.3473923 , 0.76708642],
       [0.327637  , 0.56146484],
       [0.60069985, 0.67120433],
       [0.65912225, 0.61330679],
       [0.02848829, 0.81586779],
       [0.97071949, 0.69043104],
       [0.74687514, 0.4076926 ]])

In [35]:
np.random.random_sample((4,7))

array([[0.90437524, 0.4179849 , 0.22286833, 0.70612566, 0.6298515 ,
        0.63901092, 0.87222285],
       [0.47847355, 0.54436571, 0.92699061, 0.43125351, 0.07622587,
        0.26890114, 0.36093676],
       [0.1214629 , 0.44255339, 0.78677781, 0.83253908, 0.41865806,
        0.04268368, 0.67883984],
       [0.34765348, 0.19345658, 0.78955706, 0.51513428, 0.14208492,
        0.53187072, 0.07467078]])

In [36]:
np.random.random_sample(a.shape)

array([[0.22103166, 0.10093431, 0.13228368, 0.16702031, 0.02520893,
        0.73589675, 0.2469897 ],
       [0.70182658, 0.97610469, 0.65790017, 0.80496152, 0.66905474,
        0.66526796, 0.52222004]])

In [37]:
# Random Integer values
np.random.randint(5,8, size=(3,3)) 

array([[6, 6, 7],
       [7, 6, 5],
       [7, 6, 6]], dtype=int32)

In [38]:
# Random Integer values
np.random.randint(-4,8, size=(3,3)) 

array([[ 1,  4, -3],
       [-1,  6,  4],
       [ 5, -2, -4]], dtype=int32)

In [39]:
# The identity matrix, always going to be square matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# The identity matrix, always going to be square matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [41]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [42]:
#Question: Make an array look like this: 
#https://ibb.co/1Y11hZqX

In [43]:
ques = np.ones((5,5))
ques

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
# ques[1, 1:4] = 0 
# ques[3, 1:4] = 0 
# ques[2, 1] = 0 
# ques[2, 3] = 0 
# ques[2, 2] = 9
# ques

In [45]:
ques[[1, 3], 1:4] = 0
ques[2, [1, 2, 3]] = [0, 9, 0]
ques

# ques[[1, 3], 1:4] = 0 → Sets rows 1 and 3, columns 1 to 3 to 0.
# ques[2, [1, 2, 3]] = [0, 9, 0] → Sets specific values in row 2 at columns 1, 2, 3

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

##### Be careful when copying arrays!!!

In [46]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b) 

#THIS ERROR IS NO MORE THERE IN NUMPY WE CAN DIRECTLY COPY 
#AN ARRAY AND CHANGE IT'S ELEMENTS AND IT WON'T CHANGE THE ELEMENT OF ORIGINAL ARRAY

[1 2 3]
[100   2   3]


### Mathematics

In [47]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [48]:
a + 2

array([3, 4, 5, 6])

In [49]:
a - 2

array([-1,  0,  1,  2])

In [50]:
a * 2

array([2, 4, 6, 8])

In [51]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [52]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [53]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [54]:
# Take the sin
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [55]:
a ** 2

array([ 1,  4,  9, 16])

In [56]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Statistics

In [57]:
# before = np.array([[1,2,3,4],[5,6,7,8]])
# print(before)

# after = before.reshape((4,2))
# print(after)

In [58]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.min(stats)

np.int64(1)

In [60]:
np.max(stats, axis=0)

array([4, 5, 6])

In [61]:
np.max(stats, axis=1)

array([3, 6])

In [62]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Linear Algebra

In [63]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b) #matrix multiplication

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])