# Python Numpy Arrays

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

# Array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [2]:
## import the library
import numpy as np

In [3]:
lst = [1,2,3,4]
arr =np.array(lst) 
#creates single dimensional or 1D array. 
#Number of square braackets [] = it's dimension.
#1d = [1 2 3 4] , 2d = [[1 2 3 4]]

In [4]:
type(arr)

numpy.ndarray

In [5]:
#the .shape attribute returns a tuple representing the dimensions of an array in the format (rows, columns)
arr.shape 

(4,)


### 2D ARRAY CREATION


In [6]:
lst1 = [1,2,3,4]
lst2 = [2,2,3,4]
lst3 = [3,2,3,4]
arr2d = np.array([lst1,lst2,lst3])

In [7]:
arr2d

array([[1, 2, 3, 4],
       [2, 2, 3, 4],
       [3, 2, 3, 4]])

In [8]:
arr2d.shape

(3, 4)

### INDEXING in 1D ARRAY

In [9]:
arr

array([1, 2, 3, 4])

In [10]:
arr[1] #prints 0 index elements of 1d array

np.int64(2)

In [11]:
arr[1]=5 #changing element

In [12]:
arr

array([1, 5, 3, 4])

In [13]:
arr [1:]

array([5, 3, 4])

In [14]:
arr [1:3]

array([5, 3])

In [15]:
arr[-1]

np.int64(4)

In [16]:
arr[:-1]

array([1, 5, 3])

In [17]:
arr[::] # prints complete array

array([1, 5, 3, 4])

In [18]:
arr[::-3]

array([4, 1])

### INDEXING in MULTIDIMENSIONAL ARRAY

In [19]:
arr2d

array([[1, 2, 3, 4],
       [2, 2, 3, 4],
       [3, 2, 3, 4]])

In [20]:
arr2d[:,1] # only prints second column

array([2, 2, 2])

In [21]:
# print 2 3 2 3
arr2d[1:,1:3]
# 1: → Selects rows from index 1 onwards (lst2 and lst3).
# 1:3 → Selects columns from index 1 to 2 (excluding index 3).

array([[2, 3],
       [2, 3]])

In [22]:
# print 2 2 3 2
arr2d[1:,0:2]

array([[2, 2],
       [3, 2]])

In [23]:
arr2d[:,2:]

array([[3, 4],
       [3, 4],
       [3, 4]])

In [24]:
arr2d[:,2:].shape

(3, 2)

In [25]:
arr2d.reshape(3,4)

array([[1, 2, 3, 4],
       [2, 2, 3, 4],
       [3, 2, 3, 4]])

### mechanism to create an array

arange() is a built-in function, creates an array of evenly spaced values, similar to Python's range(), but returns a NumPy array

In [26]:
arra = np.arange(5)
print(arra)


[0 1 2 3 4]


In [46]:
np.arange(1,10,2) # range(start, stop, step) 


array([1, 3, 5, 7, 9])

In [28]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [29]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [30]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [31]:
# Understanding the 3D Structure

# Now, let's break it into its axes:
# 2 → Two sub-arrays
# 5 → Each array has 5 rows
# 1 → Each row has only 1 column

In [32]:
arr *arr 

array([ 1, 25,  9, 16])

In [33]:
arr2d *arr2d

array([[ 1,  4,  9, 16],
       [ 4,  4,  9, 16],
       [ 9,  4,  9, 16]])

In [34]:
mean_value = np.mean(arr)
print("Mean:", mean_value)

Mean: 3.25


In [35]:
# numpy.ones() function creates a new array of the specified shape and fills it with ones.

np.ones((5,3))  #here 5 is row and 3 is column that is specified

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.zeros((4,5)) # similar to .one() in-built function

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
np.random.randint(10,50,4) .reshape(2,2)

array([[24, 46],
       [42, 10]], dtype=int32)

In [48]:
np.random.randn(5,6)

array([[ 0.13635849, -0.29649661,  0.49249172,  0.41364003, -1.23812838,
        -0.17925511],
       [ 0.30417949,  0.49552043, -0.03690335,  0.78852467,  0.58757008,
         0.38577845],
       [-0.21193997, -0.81717618, -2.26705732, -0.28544376,  0.19490677,
         0.08326221],
       [ 0.11789082,  0.7305349 , -0.41511171, -1.06712726, -2.33658504,
        -0.1223723 ],
       [-1.22378719, -0.9790659 , -0.04673361, -1.20993848, -0.59285575,
         2.26510696]])

In [51]:
np.random.random_sample((4,7))

array([[0.42182968, 0.9461766 , 0.08049201, 0.27391243, 0.10173161,
        0.87777819, 0.08175577],
       [0.26488634, 0.28121907, 0.10200598, 0.15270641, 0.81549381,
        0.93381694, 0.5691208 ],
       [0.16083568, 0.09813918, 0.68112542, 0.40113192, 0.37935653,
        0.30274846, 0.89077458],
       [0.91029654, 0.85110333, 0.07613441, 0.8409897 , 0.46689188,
        0.79963358, 0.10520128]])